services:
  - type: web
    name: uc-smarthelp
    buildCommand: cd UC-SmartHelp-main && rm -rf node_modules package-lock.json && yarn install && yarn build
    startCommand: cd UC-SmartHelp-main && yarn start
    envVars:
      - key: NODE_ENV
        value: production
