services:
  - type: web
    name: uc-smarthelp
    buildCommand: cd UC-SmartHelp-main && rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: cd UC-SmartHelp-main && npm start
    envVars:
      - key: NODE_ENV
        value: production
