services:
  - type: static
    name: uc-smarthelp
    buildCommand: cd UC-SmartHelp-main && rm -rf node_modules package-lock.json && npm install && npm run build
    staticPublishPath: ./UC-SmartHelp-main/dist
    envVars:
      - key: NODE_ENV
        value: production
